name: ALFRED CI - GUI
# temporary comment for new commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:

jobs:
  build-nodejs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./gui

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Verify GUI builds successfully
      - run: npm install -s
      - run: npm run build
      - run: npm run dev
